name: Setup Antlr4 on Ubuntu
description: Set up Antlr4.
author: Sia Codelabs

branding:
  icon: play-circle
  color: gray-dark

runs:
  using: composite
  steps:
    - name: Update APT information
      shell: bash -e {0}
      run: sudo apt update
    
    - name: Set up Antlr4
      shell: bash -e {0}
      run: sudo apt install -y antlr4
