name: Setup Antlr4 on Ubuntu
description: Set up Antlr4.
author: Sia Codelabs

branding:
  icon: play-circle
  color: gray-dark

inputs:
  antlr4-version:
    description: Antlr version to install.
    required: false
    default: "4.11"
  
  setup-java:
    description: Install JDK.
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Update APT information
      shell: bash
      run: sudo apt update
    
    - name: Set up JDK
      if: inputs.setup-java
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: temurin
    
    - name: Set up cURL
      shell: bash
      run: sudo apt install -y curl
    
    - name: Download Antlr4
      shell: bash
      run: |
        cd /usr/local/lib
        sudo curl -O http://www.antlr.org/download/antlr-${{ inputs.antlr4-version }}-complete.jar
    
    - name: Set up Antlr4
      shell: bash
      run: |
        export CLASSPATH=.:/usr/local/lib/antlr-${{ inputs.antlr4-version }}-complete.jar:$CLASSPATH
        sudo printf '#!/usr/bin/env bash\njava -Xmx500M -cp "/usr/local/lib/antlr-${{ inputs.antlr4-version }}-complete.jar:$CLASSPATH" org.antlr.v4.Tool\n' > /usr/local/bin/antlr4
        sudo chmod ugo+x /usr/local/bin/antlr4
        export PATH=/usr/local/bin:$PATH
    